"use client";

import {
    useId,
    useRef,
    useState,
    type KeyboardEvent,
    type ReactNode,
} from "react";

// ─────────────────────────────────────────────────────────────────────────────
// TABS  (A11Y-03)
// Shared, accessible tab interface used by Growth and Membership. Implements
// the WAI-ARIA Authoring Practices "Tabs" pattern, manual-activation variant:
//
//   - role=tablist / tab / tabpanel, aria-selected, aria-controls,
//     aria-labelledby, with IDs generated by useId (unique per instance).
//   - Roving tabindex: only the selected tab is in the Tab order.
//   - ArrowLeft / ArrowRight move focus (wrapping); Home / End jump to the
//     first / last tab. Focus moving does NOT select. Selection happens on
//     click, Enter or Space (native button behaviour), same as before.
//   - Only the active panel's content is mounted, so a tab's content (and its
//     data fetching) still starts on first view. Inactive panels keep an empty,
//     hidden wrapper so every aria-controls reference resolves to a real element.
//
// To add a tab, append an entry to the page's tabs array. Nothing else changes.
// ─────────────────────────────────────────────────────────────────────────────

export interface TabConfig {
    id: string;
    label: string;
    content: ReactNode;
}

interface TabsProps {
    tabs: readonly TabConfig[];
    // Falls back to the first tab when missing or not a known tab id.
    initialTabId?: string | null;
    // Accessible name for the tablist, e.g. "Membership sections".
    ariaLabel: string;
}

export default function Tabs({ tabs, initialTabId, ariaLabel }: TabsProps) {
    const baseId = useId();
    const tabRefs = useRef<Array<HTMLButtonElement | null>>([]);

    const [activeId, setActiveId] = useState<string>(
        () =>
            tabs.find((tab) => tab.id === initialTabId)?.id ??
            tabs[0]?.id ??
            ""
    );

    const handleKeyDown = (
        event: KeyboardEvent<HTMLButtonElement>,
        index: number
    ) => {
        const last = tabs.length - 1;
        let next: number;

        switch (event.key) {
            case "ArrowRight":
                next = index === last ? 0 : index + 1;
                break;
            case "ArrowLeft":
                next = index === 0 ? last : index - 1;
                break;
            case "Home":
                next = 0;
                break;
            case "End":
                next = last;
                break;
            default:
                return;
        }

        event.preventDefault();
        tabRefs.current[next]?.focus();
    };

    if (tabs.length === 0) return null;

    return (
        <div>
            <div
                role="tablist"
                aria-label={ariaLabel}
                className="mx-auto max-w-6xl px-4 sm:px-6 pt-2 flex gap-6 text-sm font-medium overflow-x-auto scrollbar-hidden whitespace-nowrap"
            >
                {tabs.map((tab, index) => {
                    const isActive = tab.id === activeId;

                    return (
                        <button
                            key={tab.id}
                            ref={(node) => {
                                tabRefs.current[index] = node;
                            }}
                            type="button"
                            role="tab"
                            id={`${baseId}-tab-${tab.id}`}
                            aria-selected={isActive}
                            aria-controls={`${baseId}-panel-${tab.id}`}
                            tabIndex={isActive ? 0 : -1}
                            onClick={() => setActiveId(tab.id)}
                            onKeyDown={(event) => handleKeyDown(event, index)}
                            className={`flex min-h-12 items-center py-2 cursor-pointer text-base ${isActive
                                ? "border-b-4 border-gray-300 text-foreground font-semibold" // active
                                : "border-b-4 border-transparent text-gray-500 hover:text-gray-600 font-semibold" // inactive
                                }`}
                        >
                            {tab.label}
                        </button>
                    );
                })}
            </div>

            {tabs.map((tab) => {
                const isActive = tab.id === activeId;

                return (
                    <div
                        key={tab.id}
                        role="tabpanel"
                        id={`${baseId}-panel-${tab.id}`}
                        aria-labelledby={`${baseId}-tab-${tab.id}`}
                        hidden={!isActive}
                        tabIndex={0}
                        className="w-full mx-auto focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-primary"
                    >
                        {isActive ? tab.content : null}
                    </div>
                );
            })}
        </div>
    );
}